name: "o-kernel"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  kernel-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run °
    - run: npm run °npm
    - run: npm run build
      env:
        Environment: production
    - name: remove old index.html
      run: |
        rm static/index.html
        mv static/devomoearth.html static/index.html
        mv static/* dist/
    - name: push action
      id: bucket
      uses: textileio/github-action-buckets@v20
      with:
        key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
        secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
        bucket: 'omo-marketplace-dev'
        thread: 'bafk3hjqnsapk7bbedswqq5pfhi3jue3kq7h6wnhgd5o7eedlrkroeva'
        path: 'dist'
    - run: echo "bucket - ${{ steps.bucket.outputs.key }}"
    - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
    - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
    - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
    - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
    - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
    - run: echo "www - ${{ steps.bucket.outputs.www }}"
